// FAKE DATA
export const books = [
    {
      id: 1,
      title: "Crack the Coding Interview",
      url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
      originalPrice: 49.95,
      salePrice: 14.95,
      rating: 4.5,
      summary: " Cracking the coding interview is mostly about being a great problem solver and emotionally balanced. The rest is about doing everything right on the day of your interview.",
    },
    {
      id: 2,
      title: "Atomic Habits",
      url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
      originalPrice: 39,
      salePrice: null,
      rating: 5,
      summary: "An atomic habit is a regular practice or routine that is not only small and easy to do but is also the source of incredible power; a component of the system of compound growth.",
    },
    {
      id: 3,
      title: "Can't Hurt Me",
      url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
      originalPrice: 29,
      salePrice: null,
      rating: 5,
      summary: " Can’t Hurt Me is the story of David Goggins, who went from being overweight and depressed to becoming a record-breaking athlete, inspiring military leader, and world-class personal trainer.",
    },
    {
      id: 4,
      title: "Deep Work",
      url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
      originalPrice: 44,
      salePrice: 19,
      rating: 4.5,
      summary: "Deep work is the ability to focus without distraction on a cognitively demanding task.",
    },
    {
      id: 5,
      title: "The 10X Rule",
      url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
      originalPrice: 32,
      salePrice: null,
      rating: 5,
      summary: " The 10X Rule breaks down the anatomy of extraordinary success by first pointing out what’s wrong with shooting for average, why you should for ten times more when tackling your goals and how to back up your new, bold targets with the right actions.",
    },
    {
      id: 6,
      title: "Sell Or Be Sold",
      url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
      originalPrice: 70,
      salePrice: 12.5,
      rating: 5,
      summary: "When most people hear the word “salesperson,” they think of professionals in stores who encourage them to buy things. In fact, everyone is a salesperson—whenever you need to influence, persuade, negotiate, or even just communicate with someone, you are selling.",
    },
    {
      id: 7,
      title: "Rich Dad Poor Dad",
      url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
      originalPrice: 11,
      salePrice: 10,
      rating: 4,
      summary: "Rich Dad Poor Dad is about Robert Kiyosaki and his two dads—his real father (poor dad) and the father of his best friend (rich dad)—and the ways in which both men shaped his thoughts about money and investing. You don’t need to earn a high income to be rich. Rich people make money work for them. The poor and the middle-class work for money.",
    },
    {
      id: 8,
      title: "Cashflow Quadrant",
      url: "https://covers.openlibrary.org/b/id/1954899-L.jpg",
      originalPrice: 38,
      salePrice: 17.95,
      rating: 4.5,
      summary: "Cashflow Quadrant Book Summary Cashflow Quadrant Categories Description Employee You have a job Self-employed You own a job Business Owner You own a system and people work for you Investor Money works for you ",
    },
    {
      id: 9,
      title: "48 Laws of Power Summary",
      url: "https://covers.openlibrary.org/b/id/8906626-L.jpg",
      originalPrice: 35,
      salePrice: 19.95,
      rating: 4.5,
      summary: "The 48 Laws of Power was written by Robert Greene. The book is a list of principles illustrated by real-life stories that one should respect if one hopes to rise in society and become powerful. It taught me that mastering your emotions is the most important skill you will learn in your quest for power. ",
    },
    {
      id: 10,
      title: "The 5 Second Rule",
      url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
      originalPrice: 40,
      salePrice: null,
      rating: 5,
      summary: " The 5 Second Rule by Mel Robbins Analysis and Summary Application Ideas. Over time, as you repeat the Rule, you destroy that system altogether. ",
    },
    {
      id: 11,
      title: "How to Win Friends & Influence People",
      url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
      originalPrice: 30,
      salePrice: 20,
      rating: 5,
      summary: "How to Win Friends and Influence People talks about Ninety-nine times out of a hundred, people don’t criticize themselves for anything, no matter how wrong it may be & an effective approach deal with people without offending them",
    },
    {
      id: 12,
      title: "Mastery",
      url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
      originalPrice: 30,
      salePrice: 12.95,
      rating: 4.5,
      summary: "In Mastery, Robert Greene, famous for The 48 Laws of Power, argues that there is a clear path anyone can follow to achieve mastery, the highest level of creative excellence. He explains the three stages of mastery, and he argues that pursuing it yields a fulfilling life and great creative power.",
    },
  ];

